version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run Flake8 and Black
          command: |
            flake8
            black --check .

      - run:
          name: Run Unit Tests
          command: |
            python test_calculator.py    

workflows:
  version: 2
  build:
    jobs:
      - build
