version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current-22.04

    steps:
      - checkout

      # Installez clang-format
      - run:
          name: Install clang-format
          command: sudo apt-get update && sudo apt-get install -y clang-format

      # Installez clang-tidy
      - run:
          name: Install clang-tidy
          command: sudo apt-get install -y clang-tidy

      # Exécutez clang-format pour vérifier le style
      - run:
          name: Check code style with clang-format
          command: clang-format --version && clang-format -n ./*.cpp

      # Exécutez clang-tidy pour analyser le code
      - run:
          name: Run clang-tidy
          command: clang-tidy --version && clang-tidy ./*.cpp

      # Exécutez votre script de test
      - run:
          name: Run tests
          command: ./test.sh

workflows:
  version: 2
  build:
    jobs:
      - build
